In [8]:
import cv2
import numpy as np
import os
import glob

In [9]:
ref_image = cv2.imread('./cb_grids/images/grids_5by4/02.jpg')
ref_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


CHECKERBOARD = (10,11)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

objpoints = []
imgpoints = [] 

objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

In [11]:
# images = glob.glob('./cropped_images/*.png')

# for fname in images:
#     img = cv2.imread(fname)
#     img = cv2.resize(img, (0, 0), fx = 5.0, fy = 5.0)
#     gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    
#     # Color-segmentation to get binary mask
#     lwr = np.array([0, 0, 143])
#     upr = np.array([179, 61, 252])
#     hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
#     msk = cv2.inRange(hsv, lwr, upr)

#     # Extract chess-board
#     krn = cv2.getStructuringElement(cv2.MORPH_RECT, (50, 30))
#     dlt = cv2.dilate(msk, krn, iterations=5)
#     res = 255 - cv2.bitwise_and(dlt, msk)

#     # Displaying chess-board features
#     res = np.uint8(res)
    
#     ret, corners = cv2.findChessboardCorners(res, CHECKERBOARD, flags = cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
#     # If desired number of corners are found in the image then ret = true
#     print(ret)
#     if ret == True:
#         objpoints.append(objp)
#         print("ok1")
#         corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
#         print("ok2")
#         imgpoints.append(corners2)
#         print(corners2)
#         img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
#     cv2.imshow('img',img)
#     cv2.waitKey(0)
 
# cv2.destroyAllWindows()
 
# h,w = img.shape[:2]

images = glob.glob('./cropped_images/*.png')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
#     img = cv2.imread(fname)
# #     img = cv2.resize(img, (0, 0), fx = 5.0, fy = 5.0)
#     gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    
    # Color-segmentation to get binary mask
    lwr = np.array([0, 0, 143])
    upr = np.array([179, 61, 252])
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    msk = cv2.inRange(hsv, lwr, upr)

    # Extract chess-board
    krn = cv2.getStructuringElement(cv2.MORPH_RECT, (50, 30))
    dlt = cv2.dilate(msk, krn, iterations=5)
    res = 255 - cv2.bitwise_and(dlt, msk)

    # Displaying chess-board features
    res = np.uint8(res)
#     cv2.imshow('res', res)
#     cv2.imshow('img',img)
#     cv2.waitKey(0)
 
#     cv2.destroyAllWindows()
    
    ret, corners = cv2.findChessboardCorners(res, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    print(ret)
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
#         cv2.imshow('img',img)
#         cv2.waitKey(0)

#         cv2.destroyAllWindows()

#         h,w = img.shape[:2]

        """
        Performing camera calibration by 
        passing the value of known 3D points (objpoints)
        and corresponding pixel coordinates of the 
        detected corners (imgpoints)
        """
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, ref_gray.shape[::-1], None, None)

print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

True
True
True
True
False
False
False
True
True
False
True
True
True
True
False
True
True
False
True
False
Camera matrix : 

[[9.80721207e+03 0.00000000e+00 4.51934092e+02]
 [0.00000000e+00 9.52128498e+03 7.00593695e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist : 

[[-7.47841512e+00  5.81893383e+02 -1.61932466e-01 -7.35636601e-02
  -9.71425422e-01]]
rvecs : 

(array([[-0.27781369],
       [-0.53396503],
       [ 1.47572518]]), array([[-0.15476715],
       [-0.03834501],
       [ 1.53630911]]), array([[0.35988046],
       [0.30247656],
       [1.52075201]]), array([[0.32832731],
       [0.16901342],
       [1.54133278]]), array([[0.4627034 ],
       [0.08303043],
       [1.49041229]]), array([[-0.08251841],
       [-0.30747358],
       [ 1.51986941]]), array([[0.09930817],
       [0.21945263],
       [1.53995617]]), array([[ 0.14779855],
       [-0.24634953],
       [ 1.54758239]]), array([[-0.40247505],
       [-0.13920527],
       [ 1.47427994]]), array([[-0.18582681],
  