In [69]:
# # Final Code for 3x3 checker image to detect and draw chessboard corners. Also, the calibration!
# import cv2 as cv
# import numpy as np
# import matplotlib.pyplot as plt
# import os
# import glob 
# from PIL import Image
# from datetime import datetime
# #### This file is for calibrating 3x3 frames checker board

# imn = 'C:/Users/AMIT KUMAR/01.jpg'
# #imn = 'D:/Vein Viewer/Calibration/Images/02.jpg'
# img = cv.imread(imn,2)
# ret, bw_img = cv.threshold(img, 127, 255, cv.THRESH_BINARY)
# # b,g,r = cv.split(img)

# # grey = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
# # grey = cv.threshold(img1,cv.GRAY)
# #grey = img
# print(bw_img.shape)
# print(type(bw_img))
# # cv.imshow("Binary", bw_img)
# # cv.waitKey(0)
# # cv.destroyAllWindows()
# #cv.imshow('red_img', grey)
# #cv.waitKey() 



In [70]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import os
import glob 
from PIL import Image
from datetime import datetime
#### This file is for calibrating 3x3 frames checker board

imn = './cb_grids/images/grids_5by4/02.jpg'
#imn = 'D:/Vein Viewer/Calibration/Images/02.jpg'
img = cv.imread(imn)

b,g,r = cv.split(img)

grey = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

#grey = img
print(grey)
print(grey.shape)

# cv.imshow('red_img', img)
# cv.waitKey() 

# cv.destroyAllWindows()


# # Final Code for 3x3 checker image to detect and draw chessboard corners. Also, the calibration!
# import cv2 as cv
# import numpy as np
# import matplotlib.pyplot as plt
# import os
# import glob 
# from PIL import Image
# from datetime import datetime
# #### This file is for calibrating 3x3 frames checker board

# imn = 'C:/Users/AMIT KUMAR/rch1.jpg'
# # imn = 'D:/Vein Viewer/Calibration/Images/02.jpg'
# img = cv.imread(imn)

# b,g,r = cv.split(img)

# grey = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
# #grey = img
# print(grey.shape)

# #cv.imshow('red_img', grey)
# #cv.waitKey() 

[[134 134 125 ... 148 145 141]
 [130 132 127 ... 146 146 139]
 [133 132 128 ... 150 149 142]
 ...
 [ 23  20  22 ...  64  60  54]
 [ 25  21  24 ...  65  59  52]
 [ 22  17  28 ...  60  57  58]]
(3472, 4640)


In [71]:
# # Final Code for 3x3 checker image to detect and draw chessboard corners. Also, the calibration!
# import cv2 as cv
# import numpy as np
# import matplotlib.pyplot as plt
# import os
# import glob 
# from PIL import Image
# from datetime import datetime
# #### This file is for calibrating 3x3 frames checker board

# imn = 'C:/Users/AMIT KUMAR/rch1.png'
# #imn = 'D:/Vein Viewer/Calibration/Images/02.jpg'
# img = cv.imread(imn)

# b,g,r = cv.split(img)

# grey = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
# #grey = img
# print(grey.shape)

# #cv.imshow('red_img', grey)
# #cv.waitKey() 

In [72]:
# circles = cv.HoughCircles(bw_img,cv.HOUGH_GRADIENT,1,250,
#                             param1=47,param2=30,minRadius=28,maxRadius=39)
# circles=np.array(circles)
# print(type(circles))
# print(circles)
# # circles = np.uint16(np.around(circles))
# # print(circles)

In [73]:
# circles = cv.HoughCircles(grey,cv.HOUGH_GRADIENT,1,250,
#                             param1=70,param2=20,minRadius=13,maxRadius=20)

# circles = np.uint16(np.around(circles))
# # print(circles)

In [74]:
rows = grey.shape[0]

circles = cv.HoughCircles(grey,cv.HOUGH_GRADIENT,1, 250, param1=40,param2=26,minRadius=28,maxRadius=38)

circles = np.uint16(np.around(circles))
# print(circles)

In [75]:
for i in circles[0,:]:
    # draw the outer circle
    cv.circle(img,(i[0],i[1]),i[2],(0,255,0),5)
    # draw the center of the circle
    # cv.circle(grey,(i[0],i[1]),i[2],(0,0,255),3)
# cv.imshow('detected circles',grey)
# cv.waitKey(0)
# cv.destroyAllWindows()
print(circles)
print(circles.shape)

[[[2672 1760   33]
  [3458 1676   31]
  [1206 1030   32]
  [2720  272   33]
  [2082 2524   31]
  [1976  294   35]
  [3462 2500   30]
  [ 494 1854   33]
  [1154  308   35]
  [1944  964   33]
  [ 514 1070   31]
  [1232 1776   36]
  [4108 2402   29]
  [ 536 2574   33]
  [3468 3104   31]
  [4372  404   37]
  [1304 2602   32]
  [3454  282   30]
  [2038 3150   29]
  [1292 3252   33]
  [ 432  304   31]
  [4104 1684   30]
  [2060 1772   34]
  [2710 2482   31]
  [2750  980   29]
  [4108 3080   29]
  [ 568 3306   33]
  [4084  284   31]
  [3438 1008   31]
  [ 880 2674   37]
  [3848 1830   29]
  [4022  992   28]
  [2748 3118   29]
  [3324 2808   33]
  [ 930 3042   31]]]
(1, 35, 3)


In [76]:
scale_percent = 20 # percent of original size
width = int(grey.shape[1] * scale_percent / 100)
height = int(grey.shape[0] * scale_percent / 100)
dim = (width, height)
dim1=(700,700)
# resize image
resized = cv.resize(img, dim)
cv.imshow('resized_image', resized)
cv.waitKey() 

-1

In [81]:
imcount = 0 #To keep count of the number of successfully saved frames, and to number saved the image files

for i in circles[0, :]:
    center1 = (i[0], i[1])
    for j in circles[0, :]:
        center2 = (j[0], j[1])
        x = center1[0]
        w = int(center2[0]) - int(center1[0])
        y = center1[1]
        h = int(center2[1]) - int(center1[1])
        if w<900 and w>500 and h<900 and h>500:
#             print(h)
#             print(w)
#             print(" ")
#             print(True)
#             crop_image = img[int(x):int(x+w), int(y):int(y+h)]
            imcount = imcount+1
            crop_image = img[center1[1]:center2[1], center1[0]:center2[0]]
#             print(crop_image)
# crop_image = img2[100:200, 0:100]
            cv.imwrite("./cropped_images/crop"+str(imcount)+".png", crop_image)

In [16]:
new = ([1283, 1, 15], [1301, 1070, 15])
#new = [1283, 1, 15.5]
circles = np.vstack((circles[0,:],new))
print(circles)    

[[2138 1738   33]
 [4214  442   35]
 [2032  316   33]
 [1298 1026   34]
 [1410 3216   31]
 [ 580 1848   33]
 [4036 2286   29]
 [1414 2568   31]
 [1230  320   35]
 [2730  306   32]
 [ 680 3308   35]
 [4504 2476   34]
 [ 582 1068   31]
 [2716 1714   29]
 [1328 1756   33]
 [ 636 2572   32]
 [3972  328   29]
 [2014  958   34]
 [3404  326   31]
 [3476 2968   29]
 [ 506  304   34]
 [2128 3084   32]
 [4016 1624   30]
 [3458 2402   35]
 [3408  996   33]
 [2764 2404   31]
 [2170 2468   29]
 [2776  976   29]
 [3684 2886   32]
 [2804 3022   37]
 [3438 1622   28]
 [1283    1   15]
 [1301 1070   15]]


In [ ]:
temp = circles[:,0:2]
#print(temp.shape)
gs = 4
grid = np.zeros((2,gs,gs))
# print(temp)
ind = np.lexsort((temp[:,1],temp[:,0]))
# print(temp[ind,:])
gp = temp[ind,:]
print(gp)
# print(m)
# print(gp[4,0]) 

In [ ]:
g1 = np.copy(gp)
max = 2000
for i in range(0,gs):  
    for j in range(0,gs):
        # print('j=',j)
        m = max
        u = i*gs
        v = u + gs
        
        while u < v:
            # print(u)
            if g1[u,1] < m:
                m = g1[u,1]
                indu = u
            u = u + 1
            grid[0,i,j] = g1[indu,0]
            grid[1,i,j] = g1[indu,1]
        g1[indu,1] = max
# print(grid) 
intgrid= grid.astype(int)
print(intgrid)
# print(gp) 
# print(grid[:,0,0])

In [18]:
xgrid = np.transpose(intgrid[0,:,:])
print("xgrid=",xgrid)
ygrid = np.transpose(intgrid[1,:,:])
print("ygrid=",ygrid)

# p=0
# for i in range(0,3):
#     for j in range(0,3): 

#         image_arr = grey[ygrid[j,i]:ygrid[j+1,i+1],xgrid[j,i]:xgrid[j+1,i+1]]
#         image = Image.fromarray(image_arr)
#         image.show() 
#         status = cv.imwrite('/Users/surajkumar/Documents/TIFR/veinimaging/calib_recon/frames33/croppedimage'+str(p)+'.jpg',image_arr)
#         p+=1



xgrid= [[ 436 1154 1283 1976]
 [ 514 1208 1301 1944]
 [ 488 1234 1301 2060]
 [ 488 1234 1301 2060]]
ygrid= [[ 298  308    1  294]
 [1072 1028 1070  964]
 [1852 1772 2000 1770]
 [2000 2000 2000 2000]]


In [19]:
# Defining the dimensions of checkerboard
CHECKERBOARD = (10,11)
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
world_scaling = 1
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = [] 
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 

# Defining the world coordinates for 3D points
points = objp = np.zeros((CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
p = objp[:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
objp = world_scaling*objp
# print(p)
p = 0
# prev_img_shape = None 
for i in range(0,3):
    for j in range(0,3): 
        image_arr = grey[ygrid[j,i]:ygrid[j+1,i+1],xgrid[j,i]:xgrid[j+1,i+1]]
        image = Image.fromarray(image_arr)
        # image.show() 
        status1 = cv.imwrite('./cropped_images/crop_image'+str(p)+'.jpg',image_arr)
        # print('image is saved', status)
        # print('p=', p)
        
        images = './cropped_images/crop_image'+str(p)+'.jpg'
        img = cv.imread(images) 
        gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)

        ret, corners = cv.findChessboardCorners(gray, CHECKERBOARD, 
                                                flags = cv.CALIB_CB_ADAPTIVE_THRESH +
                                                        cv.CALIB_CB_FAST_CHECK + 
                                                        cv.CALIB_CB_NORMALIZE_IMAGE)

        print('ret=',ret)
        # image.show()     


# If desired number of corners are detected, we refine the pixel coordinates and display them on the images of checker board
        
        if ret == True:
            # print("true")
            objpoints.append(objp)
            # refining pixel coordinates for given 2d points.
            corners2 = cv.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
            
            imgpoints.append(corners2)

            # Draw and display the corners
            img = cv.drawChessboardCorners(img, CHECKERBOARD, corners2,ret)
            # print(f'Loop Number{i}')
            status2 = cv.imwrite('./det_images/detected_image'+str(p)+'.jpg',img)
            print('image saved to folder', status2)
            cv.imshow('image'+str(p),img)

            #writing the images in a folder output_images
            # cv.imwrite('/Users/surajkumar/Documents/TIFR/veinimaging/calib_recon3x3/cropped_images/image{}.png'.format(bb), img)

            cv.waitKey()
            cv.destroyAllWindows()
            h,w = img.shape[:2]
            # print(h,w)

# #  Performing camera calibration by  passing the value
#  of known 3D points (objpoints) and corresponding 
# pixel coordinates of the  detected corners (imgpoints)
            ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

#         # rvecs = rotational vector
#         # tvecs = translation vector
#         # dist  = distortion coefficient
#         # camera matrix = Intrinsic camera parameters  

#         # print("Camera matrix : \n") 
            print(mtx)
            print("dist : \n")
            print(dist)
            print("rvecs : \n")
            print(rvecs)
            print("tvecs : \n")
            print(tvecs)
            print("Calibration done using image",p)
            p+=1
        else:
            print("Desired number of corners are not detected for Image ", p)
            p+=1


# Note: When performed on the 3x3 checker board, image 6 is not recognised due to image quality. 
# Hence, you see only 8 of 9 detected corner images

ret= False
Desired number of corners are not detected for Image  0
ret= False
Desired number of corners are not detected for Image  1
ret= False
Desired number of corners are not detected for Image  2
ret= False
Desired number of corners are not detected for Image  3
ret= False
Desired number of corners are not detected for Image  4
ret= False
Desired number of corners are not detected for Image  5
ret= False
Desired number of corners are not detected for Image  6
ret= False
Desired number of corners are not detected for Image  7


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:801: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'
